# Generated by Django 5.0.7 on 2024-08-19 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SNAPTRADE', 'SnapTrade'), ('PLAID', 'Plaid')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('buying_power', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('target_weighting', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('parent_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='portfolio.assetgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Groups',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('target_weighting', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('parent_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='portfolio.assetgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
            },
        ),
        migrations.CreateModel(
            name='OtherAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_weighting', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('ghost', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('parent_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assets', to='portfolio.assetgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Other Asset',
                'verbose_name_plural': 'Other Assets',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_weighting', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('ghost', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SNAPTRADE', 'SnapTrade'), ('PLAID', 'Plaid')], default='MANUAL', max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('shares_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='portfolio.account')),
                ('parent_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_assets', to='portfolio.assetgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security',
                'verbose_name_plural': 'Securities',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('BUY_TO_OPEN', 'Buy to Open'), ('BUY_TO_CLOSE', 'Buy to Close'), ('SELL_TO_OPEN', 'Sell to Open'), ('SELL_TO_CLOSE', 'Sell to Close'), ('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('RENTAL_INCOME', 'Rental Income'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('CONTRIBUTION', 'Contribution'), ('TRANSFER', 'Transfer'), ('FEE', 'Fee'), ('EXPENSE', 'Expense'), ('PAYMENT', 'Payment'), ('APPRECIATION', 'Appreciation'), ('DEPRECIATION', 'Depreciation'), ('OTHER', 'Other')], max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('liability_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.liability')),
                ('other_asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.otherasset')),
                ('security_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.security')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddIndex(
            model_name='assetgroup',
            index=models.Index(fields=['name'], name='portfolio_a_name_9d1588_idx'),
        ),
        migrations.AddIndex(
            model_name='assetgroup',
            index=models.Index(fields=['sort'], name='portfolio_a_sort_2cfc90_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetgroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['name'], name='portfolio_l_name_1bf89d_idx'),
        ),
        migrations.AddIndex(
            model_name='otherasset',
            index=models.Index(fields=['name'], name='portfolio_o_name_0ac688_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['symbol'], name='portfolio_s_symbol_65bd02_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='portfolio_t_transac_374fda_idx'),
        ),
    ]
