# Generated by Django 5.0.7 on 2024-08-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_otherasset_ghost_alter_security_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SNAPTRADE', 'SnapTrade'), ('PLAID', 'Plaid')], max_length=20),
        ),
    ]
